id: P010352
initial_creation_type: ocr
source_metadata:
  id: bdr:W30319
  title: བསམ་གཞིགས་ཉུལ་བའི་ཟིན་ཐོ
  author: ''
  volumes:
    fe4b9069a58d4e86a727b8394d412b97:
      image_group_id: I6090
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
